//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DanfeSharp.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DanfeSharp.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;NFe xmlns=&quot;http://www.portalfiscal.inf.br/nfe&quot;&gt;
        ///   &lt;infNFe Id=&quot;NFe52171004621624000349550000001227291432126856&quot; versao=&quot;3.10&quot;&gt;
        ///      &lt;ide&gt;
        ///         &lt;cUF&gt;52&lt;/cUF&gt;
        ///         &lt;cNF&gt;43212685&lt;/cNF&gt;
        ///         &lt;natOp&gt;CONCESSIONARIA OFICINA D/E&lt;/natOp&gt;
        ///         &lt;indPag&gt;0&lt;/indPag&gt;
        ///         &lt;mod&gt;55&lt;/mod&gt;
        ///         &lt;serie&gt;0&lt;/serie&gt;
        ///         &lt;nNF&gt;122729&lt;/nNF&gt;
        ///         &lt;dhEmi&gt;2017-10-06T17:47:43-03:00&lt;/dhEmi&gt;
        ///         &lt;dhSaiEnt&gt;2017-10-06T17:47:43-03:00&lt;/dhSaiEnt&gt;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NFe52171004621624000349550000001227291432126856_nfe {
            get {
                return ResourceManager.GetString("NFe52171004621624000349550000001227291432126856_nfe", resourceCulture);
            }
        }
    }
}
